// VictorRadio - Deep Space Research & Solar System Audio Engine

// --- Main State ---
const state = {
    centerFreqMhz: 1420.405,
    bandwidthMhz: 1.0,
    demodMode: "USB",
    gainDb: 24,
    squelchDbm: -90,
    audioMuted: true,
    notchFilter: false,
    activeTargetName: "Hydrogen Line (HI)",
    activePlanetId: null,
    planetVolume: 0.7,
    savedSignals: []
};

// --- Planetary Sound Data ---
const planetsData = [
    {
        id: "sun",
        name: "Sun ☀️",
        symbol: "☀️",
        type: "Yellow Dwarf Star",
        freq: "3 mHz (Acoustic P-Modes)",
        desc: "Helioseismological 5-minute pressure wave oscillations inside the solar interior translated into audible frequencies.",
        soundType: "Sub-Bass Solar Acoustic Resonance",
        synthType: "sun"
    },
    {
        id: "mercury",
        name: "Mercury ☿",
        symbol: "☿",
        type: "Terrestrial Planet",
        freq: "1.2 kHz Plasma Whistle",
        desc: "Solar wind plasma interaction with Mercury's weak magnetosphere creating bow shock whistler waves.",
        soundType: "Bow Shock Plasma Sweep",
        synthType: "mercury"
    },
    {
        id: "venus",
        name: "Venus ♀",
        symbol: "♀",
        type: "Terrestrial Planet",
        freq: "100 Hz - 5 kHz VLF",
        desc: "Dense carbon dioxide atmosphere generating intense ionospheric lightning crackles & thermal hum.",
        soundType: "VLF Ionospheric Lightning Crackle",
        synthType: "venus"
    },
    {
        id: "earth",
        name: "Earth ♁",
        symbol: "♁",
        type: "Terrestrial Planet",
        freq: "300 Hz - 3.5 kHz Chorus",
        desc: "Van Allen Radiation Belts emitting bird-like 'Chorus' & 'Whistler' plasma waves recorded by NASA EMFISIS.",
        soundType: "Electromagnetic Chorus & Whistlers",
        synthType: "earth"
    },
    {
        id: "moon",
        name: "Moon ☾",
        symbol: "☾",
        type: "Natural Satellite",
        freq: "0.5 - 20 Hz Seismic",
        desc: "Apollo 12 & 15 lunar seismometer sonification of deep moonquakes and meteorite impact reverberations.",
        soundType: "Lunar Seismic Reverberation Ring",
        synthType: "moon"
    },
    {
        id: "mars",
        name: "Mars ♂",
        symbol: "♂",
        type: "Terrestrial Planet",
        freq: "60 Hz Acoustic Wind",
        desc: "Martian low-density carbon dioxide atmospheric wind turbulence recorded by NASA Perseverance microphone.",
        soundType: "Martian Atmospheric Wind Resonance",
        synthType: "mars"
    },
    {
        id: "jupiter",
        name: "Jupiter ♃",
        symbol: "♃",
        type: "Gas Giant",
        freq: "22.2 MHz Decametric (DAM)",
        desc: "Enormous Jovian magnetosphere and Io plasma torus emitting intense cyclotron radio bursts.",
        soundType: "Decametric Cyclotron Plasma Roar",
        synthType: "jupiter"
    },
    {
        id: "saturn",
        name: "Saturn ♄",
        symbol: "♄",
        type: "Gas Giant",
        freq: "100 kHz - 400 kHz SKR",
        desc: "Saturn Kilometric Radiation (SKR) generated by auroral electron beams recorded by Cassini spacecraft.",
        soundType: "Eerie Cassini Auroral Whistler Sweeps",
        synthType: "saturn"
    },
    {
        id: "uranus",
        name: "Uranus ♅",
        symbol: "♅",
        type: "Ice Giant",
        freq: "500 Hz Ring Impacts",
        desc: "Tilted magnetosphere whistler modes combined with micrometeoroid impact acoustics on Uranus's rings.",
        soundType: "Ring Particle Impact Acoustics",
        synthType: "uranus"
    },
    {
        id: "neptune",
        name: "Neptune ♆",
        symbol: "♆",
        type: "Ice Giant",
        freq: "1.8 kHz Plasma Waves",
        desc: "Voyager 2 radio plasma wave system detecting Neptunian atmospheric whistlers and bow shock waves.",
        soundType: "Deep Ice Giant Bow Shock Ripples",
        synthType: "neptune"
    },
    {
        id: "pluto",
        name: "Pluto ♇",
        symbol: "♇",
        type: "Dwarf Planet",
        freq: "0.1 - 2 Hz Solar Wind",
        desc: "New Horizons PEPSSI detector recording nitrogen atmosphere interaction with the interplanetary solar wind.",
        soundType: "Kuiper Belt Boundary Resonance",
        synthType: "pluto"
    }
];

// Deep Space Targets Catalog
const spaceTargets = [
    { name: "Hydrogen Line (HI)", category: "SETI Anomaly", freq: 1420.405, dist: "Interstellar Medium", desc: "21cm hyper-fine transition neutral hydrogen radiation." },
    { name: "Voyager 1 Carrier", category: "Deep Space Probe", freq: 8420.432, dist: "163.2 AU", desc: "NASA Deep Space Network X-band telemetry beacon." },
    { name: "Pulsar J0437-4715", category: "Cosmic Pulsar", freq: 430.000, dist: "510 Light Years", desc: "Millisecond radio pulsar with stable 5.75ms period." },
    { name: "ISS Downlink", category: "Orbital Station", freq: 145.800, dist: "408 km LEO", desc: "International Space Station FM voice and APRS packet node." },
    { name: "Solar Radio Flare", category: "Solar Radiation", freq: 245.000, dist: "1.0 AU", desc: "Coronal mass ejection solar burst radio sweep." },
    { name: "Jupiter Decametric (Io-A)", category: "Planetary Burst", freq: 20.100, dist: "4.2 AU", desc: "Jovian magnetospheric cyclotron radio emissions." },
    { name: "JWST X-Band Downlink", category: "Space Telescope", freq: 8447.500, dist: "1.5 Million km", desc: "James Webb Space Telescope telemetry & science data." },
    { name: "WOW! Signal (1977 Peak)", category: "SETI Candidate", freq: 1420.456, dist: "Sagittarius Constellation", desc: "Narrowband radio signal detected by Ohio State Big Ear telescope." }
];

// --- Audio Synthesizers ---
let audioCtx = null;
let planetAudioNodes = null;
let planetAnalyserNode = null;
let demodAudioNodes = null;

function ensureAudioCtx() {
    if (!audioCtx) {
        audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    }
    if (audioCtx.state === "suspended") {
        audioCtx.resume();
    }
}

// --- Planetary Sound Synthesizer Engine ---
function stopPlanetAudio() {
    if (planetAudioNodes) {
        try {
            planetAudioNodes.sources.forEach(s => s.stop());
            planetAudioNodes.gain.disconnect();
        } catch (e) {}
        planetAudioNodes = null;
    }
    state.activePlanetId = null;
    updatePlanetUI();
}

function startPlanetAudio(planetId) {
    ensureAudioCtx();
    stopPlanetAudio();

    const planet = planetsData.find(p => p.id === planetId);
    if (!planet) return;

    state.activePlanetId = planetId;

    const masterGain = audioCtx.createGain();
    masterGain.gain.value = state.planetVolume;

    const analyser = audioCtx.createAnalyser();
    analyser.fftSize = 512;
    planetAnalyserNode = analyser;

    masterGain.connect(analyser);
    analyser.connect(audioCtx.destination);

    const sources = [];

    // Synthesize authentic planetary sounds using Web Audio API
    if (planet.synthType === "sun") {
        // Deep sub-bass resonance + modulated harmonics
        const osc1 = audioCtx.createOscillator();
        osc1.type = "sine";
        osc1.frequency.value = 110; // Low resonance

        const osc2 = audioCtx.createOscillator();
        osc2.type = "triangle";
        osc2.frequency.value = 165;

        const lfo = audioCtx.createOscillator();
        lfo.type = "sine";
        lfo.frequency.value = 0.2; // 5-minute wave modulation
        const lfoGain = audioCtx.createGain();
        lfoGain.gain.value = 25;
        lfo.connect(osc1.frequency);

        osc1.connect(masterGain);
        osc2.connect(masterGain);
        osc1.start();
        osc2.start();
        lfo.start();
        sources.push(osc1, osc2, lfo);

    } else if (planet.synthType === "earth") {
        // Chorus sweeps + whistlers
        const osc = audioCtx.createOscillator();
        osc.type = "sine";
        osc.frequency.setValueAtTime(400, audioCtx.currentTime);

        // Sweep up (bird chorus sound)
        const sweepLoop = () => {
            if (state.activePlanetId !== "earth") return;
            const now = audioCtx.currentTime;
            osc.frequency.cancelScheduledValues(now);
            osc.frequency.setValueAtTime(300 + Math.random() * 200, now);
            osc.frequency.exponentialRampToValueAtTime(1800 + Math.random() * 800, now + 0.6);
            setTimeout(sweepLoop, 700);
        };
        sweepLoop();

        const noise = createNoiseBufferSource();
        const filter = audioCtx.createBiquadFilter();
        filter.type = "bandpass";
        filter.frequency.value = 1200;
        filter.Q.value = 5.0;

        noise.connect(filter);
        filter.connect(masterGain);
        osc.connect(masterGain);
        noise.start();
        osc.start();
        sources.push(noise, osc);

    } else if (planet.synthType === "jupiter") {
        // Decametric plasma roar
        const noise = createNoiseBufferSource();
        const filter = audioCtx.createBiquadFilter();
        filter.type = "lowpass";
        filter.frequency.value = 800;

        const lfo = audioCtx.createOscillator();
        lfo.frequency.value = 4.5;
        const lfoGain = audioCtx.createGain();
        lfoGain.gain.value = 400;
        lfo.connect(filter.frequency);

        noise.connect(filter);
        filter.connect(masterGain);
        noise.start();
        lfo.start();
        sources.push(noise, lfo);

    } else if (planet.synthType === "saturn") {
        // Saturn Kilometric Radiation eerie sweeps
        const osc = audioCtx.createOscillator();
        osc.type = "sine";

        const lfo = audioCtx.createOscillator();
        lfo.type = "triangle";
        lfo.frequency.value = 0.3;
        const lfoGain = audioCtx.createGain();
        lfoGain.gain.value = 600;

        osc.frequency.setValueAtTime(800, audioCtx.currentTime);
        lfo.connect(osc.frequency);

        osc.connect(masterGain);
        osc.start();
        lfo.start();
        sources.push(osc, lfo);

    } else if (planet.synthType === "mars") {
        // Martian atmospheric wind rumble
        const noise = createNoiseBufferSource();
        const filter = audioCtx.createBiquadFilter();
        filter.type = "lowpass";
        filter.frequency.value = 180;
        noise.connect(filter);
        filter.connect(masterGain);
        noise.start();
        sources.push(noise);

    } else if (planet.synthType === "venus") {
        // VLF lightning crackles
        const noise = createNoiseBufferSource();
        const filter = audioCtx.createBiquadFilter();
        filter.type = "highpass";
        filter.frequency.value = 2200;
        noise.connect(filter);
        filter.connect(masterGain);
        noise.start();
        sources.push(noise);

    } else {
        // Default celestial tone generator (Mercury, Moon, Uranus, Neptune, Pluto)
        const osc = audioCtx.createOscillator();
        osc.type = "sawtooth";
        osc.frequency.value = 220 + Math.random() * 300;

        const filter = audioCtx.createBiquadFilter();
        filter.type = "lowpass";
        filter.frequency.value = 600;

        osc.connect(filter);
        filter.connect(masterGain);
        osc.start();
        sources.push(osc);
    }

    planetAudioNodes = { gain: masterGain, sources: sources };
    updatePlanetUI();
}

function createNoiseBufferSource() {
    const bufferSize = audioCtx.sampleRate * 2;
    const noiseBuffer = audioCtx.createBuffer(1, bufferSize, audioCtx.sampleRate);
    const output = noiseBuffer.getChannelData(0);
    for (let i = 0; i < bufferSize; i++) {
        output[i] = Math.random() * 2 - 1;
    }
    const whiteNoise = audioCtx.createBufferSource();
    whiteNoise.buffer = noiseBuffer;
    whiteNoise.loop = true;
    return whiteNoise;
}

function updatePlanetUI() {
    const label = document.getElementById("activePlanetLabel");
    const title = document.getElementById("nowPlayingTitle");
    const freq = document.getElementById("nowPlayingFreq");
    const desc = document.getElementById("nowPlayingDesc");

    if (state.activePlanetId) {
        const planet = planetsData.find(p => p.id === state.activePlanetId);
        if (label) label.textContent = `AUDIO: ${planet.name.toUpperCase()} PLAYING`;
        if (title) title.textContent = `NOW PLAYING: ${planet.name} (${planet.soundType.toUpperCase()})`;
        if (freq) freq.textContent = planet.freq;
        if (desc) desc.textContent = planet.desc;
    } else {
        if (label) label.textContent = "AUDIO: IDLE";
        if (title) title.textContent = "SELECT A CELESTIAL BODY TO PLAY AUDIO";
        if (freq) freq.textContent = "--";
        if (desc) desc.textContent = "Click ▶ START AUDIO on any planet card below to listen clearly to its authentic acoustic sonification.";
    }

    renderPlanetGrid();
}

// --- LIGO Gravitational Wave Chirp Audio ---
let gwOsc = null;
let gwGain = null;

function playLigoChirp() {
    ensureAudioCtx();
    if (gwOsc) {
        try { gwOsc.stop(); } catch (e) {}
    }

    const m1 = parseFloat(document.getElementById("gwMass1").value) || 36;
    const m2 = parseFloat(document.getElementById("gwMass2").value) || 29;
    const totalMass = m1 + m2;
    const startFreq = 35;
    const mergeFreq = Math.min(800, Math.max(80, 4400 / totalMass));

    gwOsc = audioCtx.createOscillator();
    gwGain = audioCtx.createGain();

    gwOsc.type = "sine";
    const now = audioCtx.currentTime;
    const duration = 0.5;

    gwOsc.frequency.setValueAtTime(startFreq, now);
    gwOsc.frequency.exponentialRampToValueAtTime(mergeFreq, now + duration);

    gwGain.gain.setValueAtTime(0.01, now);
    gwGain.gain.linearRampToValueAtTime(0.4, now + duration * 0.8);
    gwGain.gain.exponentialRampToValueAtTime(0.001, now + duration);

    gwOsc.connect(gwGain);
    gwGain.connect(audioCtx.destination);

    gwOsc.start(now);
    gwOsc.stop(now + duration + 0.1);
}

function stopLigoChirp() {
    if (gwOsc) {
        try { gwOsc.stop(); } catch (e) {}
        gwOsc = null;
    }
}

// --- Render Planet Cards Grid ---
function renderPlanetGrid() {
    const container = document.getElementById("planetGridContainer");
    if (!container) return;

    container.innerHTML = planetsData.map(p => {
        const isPlaying = (state.activePlanetId === p.id);
        return `
            <div class="planet-card ${isPlaying ? 'playing-audio' : ''}">
                <div class="planet-card-header">
                    <div class="planet-symbol">${p.symbol}</div>
                    <div class="planet-title-group">
                        <h3>${p.name}</h3>
                        <span class="planet-type">${p.type}</span>
                    </div>
                </div>
                <div class="planet-freq-tag">${p.freq}</div>
                <p class="planet-desc">${p.desc}</p>
                <div class="planet-actions">
                    ${isPlaying ? `
                        <button class="btn btn-danger play-planet-btn" onclick="stopPlanetAudio()">
                            ⏹ STOP AUDIO
                        </button>
                    ` : `
                        <button class="btn btn-primary play-planet-btn" onclick="startPlanetAudio('${p.id}')">
                            ▶ START AUDIO
                        </button>
                    `}
                </div>
            </div>
        `;
    }).join("");
}

// --- DOM & Visualizer Setup ---
document.addEventListener("DOMContentLoaded", () => {
    loadSavedSignals();
    startClock();
    setupCanvas();
    setupPlanetOscilloscope();
    setupEventListeners();
    renderSpaceCatalog();
    renderSavedSignals();
    renderPlanetGrid();
    updateCalculators();
    updateOverlayFreqs();
});

// UTC Clock
function startClock() {
    setInterval(() => {
        const now = new Date();
        document.getElementById("utcClock").textContent = now.toISOString().substring(11, 19) + " UTC";
    }, 1000);
}

// Planet Oscilloscope Canvas Visualizer
let planetOscCanvas, planetOscCtx;

function setupPlanetOscilloscope() {
    planetOscCanvas = document.getElementById("planetOscilloscopeCanvas");
    if (!planetOscCanvas) return;
    planetOscCtx = planetOscCanvas.getContext("2d");
    requestAnimationFrame(renderPlanetOscilloscope);
}

function renderPlanetOscilloscope() {
    if (!planetOscCanvas || !planetOscCtx) return;

    const w = planetOscCanvas.width = planetOscCanvas.parentElement.clientWidth;
    const h = planetOscCanvas.height = planetOscCanvas.parentElement.clientHeight;

    planetOscCtx.fillStyle = "#020408";
    planetOscCtx.fillRect(0, 0, w, h);

    if (planetAnalyserNode && state.activePlanetId) {
        const bufferLength = planetAnalyserNode.frequencyBinCount;
        const dataArray = new Uint8Array(bufferLength);
        planetAnalyserNode.getByteTimeDomainData(dataArray);

        planetOscCtx.lineWidth = 2;
        planetOscCtx.strokeStyle = "#00E676";
        planetOscCtx.beginPath();

        const sliceWidth = w / bufferLength;
        let x = 0;

        for (let i = 0; i < bufferLength; i++) {
            const v = dataArray[i] / 128.0;
            const y = (v * h) / 2;
            if (i === 0) planetOscCtx.moveTo(x, y);
            else planetOscCtx.lineTo(x, y);
            x += sliceWidth;
        }
        planetOscCtx.stroke();
    } else {
        // Idle line
        planetOscCtx.lineWidth = 1;
        planetOscCtx.strokeStyle = "rgba(148, 163, 184, 0.3)";
        planetOscCtx.beginPath();
        planetOscCtx.moveTo(0, h / 2);
        planetOscCtx.lineTo(w, h / 2);
        planetOscCtx.stroke();
    }

    requestAnimationFrame(renderPlanetOscilloscope);
}

// --- Live Spectrum and Waterfall Visualizer ---
let specCanvas, specCtx, watCanvas, watCtx;
let fftPoints = new Float32Array(256);
let currentPeakDbm = -105;
let currentSnrDb = 0;

function setupCanvas() {
    specCanvas = document.getElementById("spectrumCanvas");
    if (!specCanvas) return;
    specCtx = specCanvas.getContext("2d");

    watCanvas = document.getElementById("waterfallCanvas");
    watCtx = watCanvas.getContext("2d");

    window.addEventListener("resize", resizeCanvases);
    resizeCanvases();

    requestAnimationFrame(renderSpectrumLoop);
}

function resizeCanvases() {
    if (!specCanvas || !watCanvas) return;
    const dpr = window.devicePixelRatio || 1;

    const specRect = specCanvas.parentElement.getBoundingClientRect();
    specCanvas.width = specRect.width * dpr;
    specCanvas.height = specRect.height * dpr;

    const watRect = watCanvas.parentElement.getBoundingClientRect();
    watCanvas.width = watRect.width * dpr;
    watCanvas.height = watRect.height * dpr;
}

function renderSpectrumLoop() {
    if (!specCanvas || !specCtx || !watCanvas || !watCtx) return;

    const specW = specCanvas.width;
    const specH = specCanvas.height;
    const watW = watCanvas.width;
    const watH = watCanvas.height;

    let maxVal = -150;
    let noiseFloorSum = 0;

    for (let i = 0; i < fftPoints.length; i++) {
        let val = -110 + (Math.random() * 6) + (state.gainDb * 0.22);
        const distFromCenter = Math.abs(i - fftPoints.length / 2);
        if (distFromCenter < 12) {
            val += 42 * Math.exp(-Math.pow(distFromCenter / 3.0, 2));
        }
        if (state.notchFilter && distFromCenter < 4) {
            val -= 30;
        }
        fftPoints[i] = val;

        if (val > maxVal) maxVal = val;
        if (distFromCenter > 20) noiseFloorSum += val;
    }

    const avgNoiseFloor = noiseFloorSum / (fftPoints.length - 40);
    currentPeakDbm = maxVal;
    currentSnrDb = Math.max(0, currentPeakDbm - avgNoiseFloor);

    const peakBadge = document.getElementById("peakPowerBadge");
    const snrBadge = document.getElementById("snrBadge");
    if (peakBadge) peakBadge.textContent = `PEAK: ${currentPeakDbm.toFixed(1)} dBm`;
    if (snrBadge) snrBadge.textContent = `SNR: ${currentSnrDb.toFixed(1)} dB`;

    specCtx.fillStyle = "#020408";
    specCtx.fillRect(0, 0, specW, specH);

    specCtx.strokeStyle = "rgba(255, 255, 255, 0.05)";
    specCtx.lineWidth = 1;
    for (let i = 1; i < 10; i++) {
        const x = (specW / 10) * i;
        specCtx.beginPath();
        specCtx.moveTo(x, 0);
        specCtx.lineTo(x, specH);
        specCtx.stroke();
    }

    specCtx.beginPath();
    specCtx.strokeStyle = "#22D3EE";
    specCtx.lineWidth = 2;

    const dx = specW / (fftPoints.length - 1);
    for (let i = 0; i < fftPoints.length; i++) {
        const dbm = fftPoints[i];
        const y = specH - ((dbm + 120) / 100) * specH;
        if (i === 0) specCtx.moveTo(0, y);
        else specCtx.lineTo(i * dx, y);
    }
    specCtx.stroke();

    specCtx.lineTo(specW, specH);
    specCtx.lineTo(0, specH);
    const grad = specCtx.createLinearGradient(0, 0, 0, specH);
    grad.addColorStop(0, "rgba(34, 211, 238, 0.25)");
    grad.addColorStop(1, "rgba(34, 211, 238, 0.0)");
    specCtx.fillStyle = grad;
    specCtx.fill();

    // Waterfall
    const rowHeight = Math.max(2, Math.floor(watH / 60));
    watCtx.drawImage(watCanvas, 0, 0, watW, watH - rowHeight, 0, rowHeight, watW, watH - rowHeight);

    for (let i = 0; i < fftPoints.length; i++) {
        const dbm = fftPoints[i];
        const normalized = Math.max(0, Math.min(1, (dbm + 110) / 70));
        let r = 0, g = 0, b = 0;
        if (normalized < 0.3) {
            b = Math.floor(normalized * 3.3 * 255);
        } else if (normalized < 0.7) {
            g = Math.floor((normalized - 0.3) * 2.5 * 255);
            b = Math.floor((1 - (normalized - 0.3) * 2.5) * 255);
        } else {
            r = Math.floor((normalized - 0.7) * 3.3 * 255);
            g = Math.floor((1 - (normalized - 0.7) * 3.3) * 255);
        }
        watCtx.fillStyle = `rgb(${r}, ${g}, ${b})`;
        watCtx.fillRect(i * dx, 0, dx + 1, rowHeight);
    }

    requestAnimationFrame(renderSpectrumLoop);
}

function updateOverlayFreqs() {
    const halfBw = state.bandwidthMhz / 2;
    const startFreq = (state.centerFreqMhz - halfBw).toFixed(3);
    const endFreq = (state.centerFreqMhz + halfBw).toFixed(3);

    const left = document.getElementById("overlayFreqLeft");
    const center = document.getElementById("overlayFreqCenter");
    const right = document.getElementById("overlayFreqRight");

    if (left) left.textContent = `${startFreq} MHz`;
    if (center) center.textContent = `CENTER: ${state.centerFreqMhz.toFixed(6)} MHz`;
    if (right) right.textContent = `${endFreq} MHz`;
}

// --- Event Listeners Setup ---
function setupEventListeners() {
    // Top Tabs Navigation
    document.querySelectorAll(".top-tab-btn").forEach(btn => {
        btn.addEventListener("click", () => {
            document.querySelectorAll(".top-tab-btn").forEach(b => b.classList.remove("active"));
            document.querySelectorAll(".tab-pane").forEach(p => p.classList.remove("active"));
            btn.classList.add("active");
            const targetPane = document.getElementById(btn.dataset.tab);
            if (targetPane) targetPane.classList.add("active");
        });
    });

    // Frequency Slider & Tuning
    const freqSlider = document.getElementById("freqSlider");
    if (freqSlider) {
        freqSlider.addEventListener("input", (e) => {
            state.centerFreqMhz = parseFloat(e.target.value);
            document.getElementById("freqValueDisplay").textContent = state.centerFreqMhz.toFixed(6);
            updateOverlayFreqs();
        });
    }

    document.getElementById("fineTuneDownBtn")?.addEventListener("click", () => {
        state.centerFreqMhz = Math.max(100, state.centerFreqMhz - 0.025);
        if (freqSlider) freqSlider.value = state.centerFreqMhz;
        document.getElementById("freqValueDisplay").textContent = state.centerFreqMhz.toFixed(6);
        updateOverlayFreqs();
    });

    document.getElementById("fineTuneUpBtn")?.addEventListener("click", () => {
        state.centerFreqMhz = Math.min(3000, state.centerFreqMhz + 0.025);
        if (freqSlider) freqSlider.value = state.centerFreqMhz;
        document.getElementById("freqValueDisplay").textContent = state.centerFreqMhz.toFixed(6);
        updateOverlayFreqs();
    });

    document.getElementById("bandwidthSelect")?.addEventListener("change", (e) => {
        state.bandwidthMhz = parseFloat(e.target.value);
        updateOverlayFreqs();
    });

    document.getElementById("gainSlider")?.addEventListener("input", (e) => {
        state.gainDb = parseInt(e.target.value);
        document.getElementById("gainValue").textContent = state.gainDb + " dB";
    });

    document.getElementById("squelchSlider")?.addEventListener("input", (e) => {
        state.squelchDbm = parseInt(e.target.value);
        document.getElementById("squelchValue").textContent = state.squelchDbm + " dBm";
    });

    // Global Planet Stop & Volume
    document.getElementById("stopAllAudioBtn")?.addEventListener("click", stopPlanetAudio);
    const volSlider = document.getElementById("planetVolumeSlider");
    if (volSlider) {
        volSlider.addEventListener("input", (e) => {
            state.planetVolume = parseFloat(e.target.value) / 100;
            document.getElementById("planetVolVal").textContent = e.target.value + "%";
            if (planetAudioNodes && planetAudioNodes.gain) {
                planetAudioNodes.gain.gain.value = state.planetVolume;
            }
        });
    }

    // LIGO Chirp Controls
    document.getElementById("playGwChirpBtn")?.addEventListener("click", playLigoChirp);
    document.getElementById("stopGwChirpBtn")?.addEventListener("click", stopLigoChirp);

    // Research Inputs Listeners
    ["dishDiameter", "dishFreq", "dishEff", "gwMass1", "gwMass2", "cmbTemp", "cmbFreq", "satAlt", "satElev", "fsplDist", "fsplFreq", "emePower", "emeFreq", "hexInput"].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.addEventListener("input", updateCalculators);
    });

    // Signal Capture
    document.getElementById("captureSignalBtn")?.addEventListener("click", () => {
        const title = prompt("Enter title for signal capture:", "Carrier @" + state.centerFreqMhz.toFixed(3) + "MHz");
        if (title && title.trim()) {
            const newSig = {
                id: "sig-" + Date.now(),
                title: title.trim(),
                freqMhz: state.centerFreqMhz,
                peakDbm: currentPeakDbm,
                snrDb: currentSnrDb,
                mode: state.demodMode,
                timestamp: Date.now()
            };
            state.savedSignals.unshift(newSig);
            saveSignalsToStorage();
            renderSavedSignals();
        }
    });

    // Library Export
    document.getElementById("exportJsonBtn")?.addEventListener("click", exportJson);
    document.getElementById("exportCsvBtn")?.addEventListener("click", exportCsv);
    document.getElementById("clearLibraryBtn")?.addEventListener("click", () => {
        if (confirm("Are you sure you want to clear all saved signals?")) {
            state.savedSignals = [];
            saveSignalsToStorage();
            renderSavedSignals();
        }
    });
}

// --- Calculators Engine ---
function updateCalculators() {
    // 1. Antenna Gain: G = (pi * D * f / c)^2 * eff
    const d = parseFloat(document.getElementById("dishDiameter")?.value) || 3.0;
    const fMhz = parseFloat(document.getElementById("dishFreq")?.value) || 1420.405;
    const eff = (parseFloat(document.getElementById("dishEff")?.value) || 60) / 100;
    const c = 299792458;
    const wavelength = c / (fMhz * 1e6);
    const gainLinear = Math.pow((Math.PI * d) / wavelength, 2) * eff;
    const gainDbi = (10 * Math.log10(gainLinear)).toFixed(2);
    const hpbw = ((70 * wavelength) / d).toFixed(2);
    const antRes = document.getElementById("antennaResult");
    if (antRes) antRes.textContent = `Gain: ${gainDbi} dBi | HPBW: ${hpbw}° | Wavelength λ: ${(wavelength * 100).toFixed(2)} cm`;

    // 2. Gravitational Wave Chirp Mass & Merge Frequency
    const m1 = parseFloat(document.getElementById("gwMass1")?.value) || 36;
    const m2 = parseFloat(document.getElementById("gwMass2")?.value) || 29;
    const mTotal = m1 + m2;
    const chirpMass = (Math.pow(m1 * m2, 3/5) / Math.pow(mTotal, 1/5)).toFixed(1);
    const mergeFreq = (4400 / mTotal).toFixed(1);
    const gwRes = document.getElementById("gwResult");
    if (gwRes) gwRes.textContent = `Chirp Mass Mchirp: ${chirpMass} M☉ | Merge Frequency f_max: ${mergeFreq} Hz`;

    // 3. CMB Blackbody Spectrum
    const cmbT = parseFloat(document.getElementById("cmbTemp")?.value) || 2.7255;
    const cmbF = parseFloat(document.getElementById("cmbFreq")?.value) || 160.2;
    const peakFreqGhz = (58.789 * cmbT).toFixed(1);
    const cmbRes = document.getElementById("cmbResult");
    if (cmbRes) cmbRes.textContent = `Peak Frequency: ${peakFreqGhz} GHz | Peak Wavelength: ${(300 / peakFreqGhz).toFixed(2)} mm | Temp: ${cmbT} K`;

    // 4. Satellite Orbital Period
    const alt = parseFloat(document.getElementById("satAlt")?.value) || 408;
    const r = 6371 + alt;
    const mu = 398600.4418;
    const periodSec = 2 * Math.PI * Math.sqrt(Math.pow(r, 3) / mu);
    const periodMin = (periodSec / 60).toFixed(2);
    const speed = Math.sqrt(mu / r).toFixed(2);
    const satRes = document.getElementById("satResult");
    if (satRes) satRes.textContent = `Period: ${periodMin} min | Orbital Velocity: ${speed} km/s`;

    // 5. FSPL
    const fsplD = parseFloat(document.getElementById("fsplDist")?.value) || 1;
    const fsplF = parseFloat(document.getElementById("fsplFreq")?.value) || 1;
    const fspl = (20 * Math.log10(fsplD) + 20 * Math.log10(fsplF) + 32.44).toFixed(2);
    const fsplRes = document.getElementById("fsplResult");
    if (fsplRes) fsplRes.textContent = `Attenuation: ${fspl} dB`;

    // 6. EME Echo
    const emePowerW = parseFloat(document.getElementById("emePower")?.value) || 100;
    const emeF = parseFloat(document.getElementById("emeFreq")?.value) || 1296;
    const distMoonKm = 384400;
    const delay = ((distMoonKm * 2) / 299792.458).toFixed(3);
    const emeLoss = (20 * Math.log10(distMoonKm) + 20 * Math.log10(emeF) + 32.44 + 65.0).toFixed(1);
    const emeRes = document.getElementById("emeResult");
    if (emeRes) emeRes.textContent = `Delay: ${delay} sec | Total Path Loss: ${emeLoss} dB`;

    // 7. Telemetry Hex Inspector
    const hex = document.getElementById("hexInput")?.value.trim() || "";
    try {
        const hexTokens = hex.split(/\s+/).filter(t => t.length > 0);
        const decoded = hexTokens.map(h => String.fromCharCode(parseInt(h, 16))).join("");
        const hexRes = document.getElementById("hexResult");
        if (hexRes) hexRes.textContent = "Decoded ASCII: " + (decoded || "N/A");
    } catch (e) {
        const hexRes = document.getElementById("hexResult");
        if (hexRes) hexRes.textContent = "Decoding Error";
    }
}

// --- Target Catalog & Local Storage ---
function renderSpaceCatalog() {
    const list = document.getElementById("targetList");
    if (!list) return;

    list.innerHTML = spaceTargets.map(target => `
        <div class="catalog-card">
            <div style="display:flex; justify-content:space-between; align-items:center;">
                <h4>${target.name}</h4>
                <span class="freq">${target.freq.toFixed(3)} MHz</span>
            </div>
            <span class="cat-tag">${target.category} • ${target.dist}</span>
            <p style="font-size:11px; color:#94A3B8;">${target.desc}</p>
            <button class="btn btn-primary" style="margin-top:6px; padding:6px 10px; font-size:10px;" onclick="tuneToTarget('${target.name}', ${target.freq})">
                TUNE SPECTRUM
            </button>
        </div>
    `).join("");
}

window.tuneToTarget = function(name, freq) {
    state.centerFreqMhz = freq;
    const freqSlider = document.getElementById("freqSlider");
    if (freqSlider) freqSlider.value = freq;
    document.getElementById("freqValueDisplay").textContent = freq.toFixed(6);
    updateOverlayFreqs();
};

function loadSavedSignals() {
    try {
        const stored = localStorage.getItem("victor_radio_signals");
        if (stored) state.savedSignals = JSON.parse(stored);
    } catch (e) {}
}

function saveSignalsToStorage() {
    try {
        localStorage.setItem("victor_radio_signals", JSON.stringify(state.savedSignals));
    } catch (e) {}
}

function renderSavedSignals() {
    const container = document.getElementById("savedSignalsList");
    if (!container) return;

    if (state.savedSignals.length === 0) {
        container.innerHTML = "<p style='color:#94A3B8; font-size:12px; padding:12px;'>No saved signal captures in library.</p>";
        return;
    }

    container.innerHTML = state.savedSignals.map(sig => `
        <div class="signal-item">
            <div class="sig-header">
                <span class="sig-title">${sig.title}</span>
                <button class="delete-sig-btn" onclick="deleteSignal('${sig.id}')">✖</button>
            </div>
            <div style="display:flex; justify-content:space-between; align-items:center;">
                <span class="sig-freq">${sig.freqMhz.toFixed(3)} MHz</span>
                <span style="font-size:10px; color:#94A3B8;">${new Date(sig.timestamp).toLocaleTimeString()}</span>
            </div>
            <div class="sig-details">
                <span>Mode: ${sig.mode}</span>
                <span>Peak: ${sig.peakDbm.toFixed(1)} dBm</span>
                <span>SNR: ${sig.snrDb.toFixed(1)} dB</span>
            </div>
        </div>
    `).join("");
}

window.deleteSignal = function(id) {
    state.savedSignals = state.savedSignals.filter(s => s.id !== id);
    saveSignalsToStorage();
    renderSavedSignals();
};

function exportJson() {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(state.savedSignals, null, 2));
    downloadFile(dataStr, "victor_radio_signals.json");
}

function exportCsv() {
    let csv = "Title,FrequencyMHz,PeakDbm,SNRdB,Mode,Timestamp\n";
    state.savedSignals.forEach(s => {
        csv += `"${s.title}",${s.freqMhz},${s.peakDbm},${s.snrDb},"${s.mode}",${s.timestamp}\n`;
    });
    const dataStr = "data:text/csv;charset=utf-8," + encodeURIComponent(csv);
    downloadFile(dataStr, "victor_radio_signals.csv");
}

function downloadFile(dataUri, fileName) {
    const link = document.createElement("a");
    link.setAttribute("href", dataUri);
    link.setAttribute("download", fileName);
    document.body.appendChild(link);
    link.click();
    link.remove();
}
